### ISSUE TITLE
Problem with R path

### ISSUE THREAD

**Issue by slequime** [thackl/detectEVE#7]
[Wed Nov 29 11:28:52 2023]
rule validate_putatEVEs:
    input: results/JAGGDN01-retro.o6
    output: results/JAGGDN01-validatEVEs.tsv, results/JAGGDN01-validatEVEs.pdf
    jobid: 6
    reason: Missing output files: results/JAGGDN01-validatEVEs.tsv, results/JAGGDN01-validatEVEs.pdf; Input files updated by another job: results/JAGGDN01-retro.o6
    wildcards: asm=JAGGDN01
    resources: tmpdir=/tmp

/usr/bin/env: invalid option -- 'S'
Try '/usr/bin/env --help' for more information.
[Wed Nov 29 11:28:52 2023]
Error in rule validate_putatEVEs:
    jobid: 6
    input: results/JAGGDN01-retro.o6
    output: results/JAGGDN01-validatEVEs.tsv, results/JAGGDN01-validatEVEs.pdf
    shell:
        /home/slequime/Tools/detectEVE/workflow/scripts/validate.R results/JAGGDN01-retro.o6 results/JAGGDN01-validatEVEs.tsv results/JAGGDN01-validatEVEs.pdf
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-11-29T112451.131977.snakemake.log

**Comment by thackl** [comment]
The problem here was that old `/usr/bin/env` does not have `-S`. I tried to solve this by replacing the shebang with `#!/usr/bin/env Rscript -S --vanilla` with `#!Rscript --vanilla`. This, however, also only seems to work on some cases. It broke things for @nbrait. She gets `/bin/bash: bad interpreter Rscript`. Not entirely sure why, I suspect something with `snakemake>shell:`.. Nadja suggested to explicitly call the script with `Rscript --vanilla validate.R ...`. That seems like a good workaround!
